-- Huawei Enterprise Shop - pages + SEO fields
USE huawei_shop;

CREATE TABLE IF NOT EXISTS pages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(160) NOT NULL,
  content MEDIUMTEXT,
  meta_title VARCHAR(200) NOT NULL DEFAULT '',
  meta_description VARCHAR(300) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE products
  ADD COLUMN meta_title VARCHAR(200) NOT NULL DEFAULT '' AFTER description,
  ADD COLUMN meta_description VARCHAR(300) NOT NULL DEFAULT '' AFTER meta_title;

ALTER TABLE categories
  ADD COLUMN meta_title VARCHAR(200) NOT NULL DEFAULT '' AFTER short_desc,
  ADD COLUMN meta_description VARCHAR(300) NOT NULL DEFAULT '' AFTER meta_title;